# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IrfODAdrHG65nB2Hhm6HflCYtIENK4eB
"""

import random
import pandas as pd
import numpy as np
from datetime import datetime, timedelta

# 1. Setup Parameters
start_date = datetime(2025, 1, 1)
end_date = datetime(2025, 12, 31, 23, 45)
interval = timedelta(minutes=15)

# REDUCED: Define only 3 companies as requested
company_info = {
    "TechNova": 150,
    "GreenGrid": 300,
    "Solaris Co": 80
}

# 2. Define 2025 Indian Holidays/Festivals
holidays_2025 = {
    '2025-01-01': 'New Year', '2025-01-14': 'Makar Sankranti', '2025-01-26': 'Republic Day',
    '2025-03-14': 'Holi', '2025-08-15': 'Independence Day', '2025-10-02': 'Gandhi Jayanti',
    '2025-10-20': 'Diwali', '2025-12-25': 'Christmas'
}

data = []
current_time = start_date

print("Generating interconnected dataset for 3 companies (No Occupancy Data)...")

while current_time <= end_date:
    date_str = current_time.strftime('%Y-%m-%d')
    hour = current_time.hour
    day_of_year = current_time.timetuple().tm_yday

    # Track Holidays and Weekends
    is_holiday = date_str in holidays_2025
    is_weekend = current_time.weekday() >= 5
    is_standard_working_day = not is_holiday and not is_weekend

    # 3. Simulate Weather
    seasonal_temp = 25 + 10 * np.sin(2 * np.pi * (day_of_year - 100) / 365)
    daily_temp = 5 * np.sin(2 * np.pi * (hour - 9) / 24)
    temp = round(seasonal_temp + daily_temp + np.random.normal(0, 0.5), 1)

    humidity_base = 50 - (daily_temp * 2)
    if 180 < day_of_year < 270: # Monsoon
        humidity_base += 30
    humidity = int(np.clip(humidity_base + np.random.normal(0, 2), 10, 100))

    # 4. Generate Data for 3 companies at this timestamp
    for company, max_employees in company_info.items():

        # --- A. Determine Internal Load Logic (Implicit Occupancy) ---
        # We calculate the load based on time/day rather than a visible occupancy column
        if is_standard_working_day:
            if 8 <= hour < 10: load_factor = random.uniform(0.4, 0.7)
            elif 10 <= hour < 17: load_factor = random.uniform(0.8, 1.0)
            elif 17 <= hour < 19: load_factor = random.uniform(0.4, 0.8)
            else: load_factor = random.uniform(0.05, 0.15)
        else:
            load_factor = random.uniform(0.01, 0.1)

        # --- B. Calculate Interconnected Power Consumption ---
        base_load = max_employees * 0.05
        # Equipment load now scales directly with the time-based load factor
        equipment_load = (max_employees * load_factor) * 0.15

        hvac_load = 0
        if temp > 26 or humidity > 65:
            weather_strain = max(0, (temp - 26) * 0.2) + max(0, (humidity - 65) * 0.1)
            # HVAC load influenced by the intensity of building use (load_factor)
            occupancy_heat_proxy = (max_employees * load_factor) * 0.08

            if load_factor > 0.1:
                hvac_load = weather_strain + occupancy_heat_proxy
            else:
                hvac_load = weather_strain * 0.2

        event_spike = 0
        if is_holiday and holidays_2025.get(date_str) == 'Diwali' and 18 <= hour <= 23:
            event_spike = max_employees * 0.2

        noise = np.random.normal(0, 0.5)
        power_consumption = round(max(0.1, base_load + equipment_load + hvac_load + event_spike + noise), 3)

        # Removed 'occupancy_count' from the list
        data.append([
            company, date_str, current_time.strftime('%H:%M:%S'),
            is_weekend, is_holiday, max_employees,
            temp, humidity, power_consumption
        ])

    current_time += interval

# 5. Create DataFrame (Removed 'occupancy_count')
columns = [
    'company_name', 'date', 'timestamp', 'is_weekend', 'is_holiday',
    'max_capacity', 'temperature', 'humidity', 'power_consumption'
]
df = pd.DataFrame(data, columns=columns)

print(f"Dataset generated successfully with {len(df)} rows.")

# Save to CSV
df.to_csv('smart_grid_dataset_2025_no_occupancy.csv', index=False)
print("\nFile 'smart_grid_dataset_2025_no_occupancy.csv' is ready.")

# CELL 0: Memory & GPU Optimization

import gc
import tensorflow as tf
import os

print("\n" + "="*70)
print("SYSTEM & MEMORY OPTIMIZATION")
print("="*70)

# 1. Check for GPU availability
gpus = tf.config.list_physical_devices('GPU')

if gpus:
    try:
        # Enable memory growth so TF doesn't "hog" the whole GPU immediately
        for gpu in gpus:
            tf.config.experimental.set_memory_growth(gpu, True)

        # Limit memory to 4GB ONLY if you are on a T4 GPU (common in Colab)
        # We wrap this in a check to prevent errors if gpus list is empty
        tf.config.set_logical_device_configuration(
            gpus[0],
            [tf.config.LogicalDeviceConfiguration(memory_limit=4096)]
        )
        print(f"✅ GPU detected: {len(gpus)} device(s). Memory growth & 4GB limit enabled.")

    except RuntimeError as e:
        # Memory configuration must be set before GPUs have been initialized
        print(f"⚠️ GPU already initialized: {e}")
    except Exception as e:
        print(f"❌ Error configuring GPU: {e}")
else:
    print("ℹ️ No GPU detected. Running on CPU mode.")

# 2. Clear system garbage collection
gc.collect()

# 3. Suppress unnecessary TensorFlow logging (keeps your console clean)
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '2'

print("✅ Memory optimization setup complete")
print("="*70)

# CELL 1: Install Dependencies

# Added 'python-multipart' for FastAPI form handling
# and 'requests' for easy testing of your own endpoints
!pip install pandas numpy tensorflow scikit-learn matplotlib joblib openpyxl fastapi uvicorn python-multipart requests -q

print("✅ All dependencies installed and ready for the backend bridge!")

# CELL 2: Upload Dataset

from google.colab import files
import os

print("\n" + "="*70)
print("📂 DATASET UPLOAD")
print("="*70)

print("Please select your dataset (CSV or Excel)...")
uploaded = files.upload()

# Check if a file was actually selected
if not uploaded:
    print("❌ Error: No file uploaded. Please run this cell again.")
else:
    # Get the file name from the uploaded dictionary
    file_name = list(uploaded.keys())[0]

    # Check file extension to guide the next step
    file_ext = os.path.splitext(file_name)[1].lower()

    print(f"\n✅ Uploaded successfully: {file_name}")
    print(f"📊 File format detected: {file_ext}")
    print(f"💾 File size: {os.path.getsize(file_name) / 1024:.2f} KB")

    # If it's an Excel file, remind the user we need openpyxl
    if file_ext in ['.xlsx', '.xls']:
        print("💡 Tip: Since this is an Excel file, ensure you use pd.read_excel() in Cell 3.")
    elif file_ext == '.csv':
        print("💡 Tip: Use pd.read_csv() in Cell 3.")
    else:
        print("⚠️ Warning: Unusual file extension. Ensure pandas can read this format.")

print("\n" + "="*70)

# CELL 3C: SAMPLE DATASET (FIXED FOR TIME SERIES)

import pandas as pd
import numpy as np
import gc

print("\n" + "="*70)
print("SAMPLING DATASET (CHRONOLOGICAL PRESERVATION)")
print("="*70)

# Load data (Your existing robust loading logic)
try:
    if file_name.endswith('.csv'):
        df = pd.read_csv(file_name)
    else:
        df = pd.read_excel(file_name)
    print(f"✅ Data loaded. Original shape: {df.shape}")
except Exception as e:
    print(f"❌ Load Error: {e}")
    raise

# CRITICAL: Convert to datetime and sort BEFORE sampling
# This ensures we don't break the sequences the LSTM needs
if 'timestamp' in df.columns:
    df['timestamp'] = pd.to_datetime(df['timestamp'])
    df = df.sort_values(['company_name', 'timestamp'])

# Sample to 10% by taking a CONTIGUOUS BLOCK (e.g., the last 10% of history)
print("\nSampling 10% of the most recent data per company...")

sampled_dfs = []
for company in df['company_name'].unique():
    company_df = df[df['company_name'] == company]

    # Calculate how many rows represent 10%
    num_rows = len(company_df)
    sample_size = max(500, num_rows // 10) # 500 min to ensure enough sequences

    # Take the LAST 10% of the data (the most recent history)
    # This keeps the time-steps connected!
    sampled = company_df.tail(sample_size)
    sampled_dfs.append(sampled)

    print(f"  {company}: {num_rows} total → keeping last {len(sampled)} rows")

df = pd.concat(sampled_dfs, ignore_index=True)

print(f"\nFinal Sampled shape: {df.shape}")
print(f"Memory usage: ~{df.memory_usage(deep=True).sum() / 1024 / 1024:.2f} MB")

# Clear memory
gc.collect()

print("\n✅ Dataset sampled! (Time-sequences preserved for LSTM)")

# CELL 3: Optimize Memory (Post-Sampling)

import pandas as pd
import numpy as np
import gc

print("\n" + "="*70)
print("OPTIMIZING SAMPLED DATA")
print("="*70)

# We do NOT re-load here. We optimize the 'df' already in memory from Cell 3C.

def optimize_memory(df):
    """
    Downcasts numeric types to save RAM.
    Crucial for LSTMs to prevent Colab from crashing.
    """
    start_mem = df.memory_usage().sum() / 1024**2

    for col in df.columns:
        # Optimize Floats
        if df[col].dtype == 'float64':
            df[col] = pd.to_numeric(df[col], downcast='float')
        # Optimize Integers
        elif df[col].dtype == 'int64':
            df[col] = pd.to_numeric(df[col], downcast='integer')

    end_mem = df.memory_usage().sum() / 1024**2
    print(f"✅ Memory reduced from {start_mem:.2f}MB to {end_mem:.2f}MB")
    return df

# Run optimization on the existing DataFrame
if 'df' in locals() or 'df' in globals():
    df = optimize_memory(df)
    gc.collect()
else:
    print("❌ Error: 'df' not found. Please run Cell 3C first!")

# 3. Final Verification
print(f"\nFinal training shape: {df.shape}")
print(f"Data types after optimization:\n{df.dtypes}")

print("\n" + "="*70)
print("✅ Ready for Data Cleaning!")
print("="*70)

# CELL 3B: Debug - Check Data Structure

print("\n" + "="*70)
print("DEBUGGING: Check Actual Data Structure")
print("="*70)

print(f"\n1. Exact Column Names:")
print(f"   {df.columns.tolist()}")

print(f"\n2. Sample Data:")
print(df.head(10))

print(f"\n3. Data Types:")
print(df.dtypes)

print(f"\n4. Check 'date' column samples:")
print(f"   {df['date'].head(10)}")
print(f"   Type: {df['date'].dtype}")

print(f"\n5. Check 'timestamp' column samples:")
print(f"   {df['timestamp'].head(10)}")
print(f"   Type: {df['timestamp'].dtype}")

print(f"\n6. Check all numeric columns:")
for col in df.columns:
    if col not in ['company_name', 'date', 'timestamp']:
        print(f"   {col}: {df[col].head(3).tolist()}")

# CELL 4: Data Cleaning and Preparation (PRODUCTION-READY)

import pandas as pd
import numpy as np

print("\n" + "="*70)
print("DATA CLEANING AND PREPARATION")
print("="*70)

# Create a fresh copy to work on
df_clean = df.copy()

# Step 1: Combine date and timestamp into single datetime column (ROBUST VERSION)
print("\nStep 1: Processing Datetime...")
try:
    # Ensure date is a string
    date_part = df_clean['date'].astype(str)

    # Extract only the time part (HH:MM:SS) if timestamp is already a datetime string
    # This prevents '2025-01-01 2025-01-01 08:00:00' errors
    time_part = df_clean['timestamp'].astype(str).str.split(' ').str[-1]

    # Combine and convert
    df_clean['timestamp'] = pd.to_datetime(
        date_part + ' ' + time_part,
        errors='coerce'
    )

    # Fallback: If conversion failed, try parsing the original timestamp column directly
    if df_clean['timestamp'].isna().all():
        df_clean['timestamp'] = pd.to_datetime(df['timestamp'], errors='coerce')

    # Also ensure the 'date' column is a proper datetime object
    df_clean['date'] = pd.to_datetime(df_clean['date'], errors='coerce')

    print("  ✅ Date and timestamp unified successfully")
except Exception as e:
    print(f"  ❌ Error in Step 1: {e}")
    raise

# Step 2: Handle Missing Occupancy (The "Flexibility" Fix)
print("\nStep 2: Checking for occupancy columns...")
# Check if occupancy exists; if not, we proceed without 'workers'
has_occupancy = 'occupancy_count' in df_clean.columns
if has_occupancy:
    df_clean['workers'] = df_clean['occupancy_count']
    print("  ✅ Created 'workers' column from 'occupancy_count'")
else:
    print("  ℹ️ occupancy_count not found. Model will use Environment/Time features only.")

# Step 3: Convert boolean columns to integers (0 and 1)
print("\nStep 3: Converting boolean columns...")
if 'is_weekend' in df_clean.columns:
    df_clean['is_weekend'] = df_clean['is_weekend'].astype(int)
if 'is_holiday' in df_clean.columns:
    df_clean['is_holiday'] = df_clean['is_holiday'].astype(int)
print("  ✅ Boolean columns converted to int")

# Step 4: Ensure numeric columns are correct type for TensorFlow
print("\nStep 4: Validating numeric columns...")
numeric_cols = ['max_capacity', 'temperature', 'humidity', 'power_consumption']
if has_occupancy:
    numeric_cols.append('workers')

for col in numeric_cols:
    if col in df_clean.columns:
        df_clean[col] = pd.to_numeric(df_clean[col], errors='coerce')
        valid_count = df_clean[col].notna().sum()
        print(f"  ✅ {col:18} | {valid_count}/{len(df_clean)} valid numbers")

# Step 5: Remove rows with invalid timestamps or missing target (Power)
print("\nStep 5: Removing invalid rows...")
initial_rows = len(df_clean)
df_clean = df_clean[df_clean['timestamp'].notna()].copy()
df_clean = df_clean[df_clean['power_consumption'].notna()].copy()
print(f"  Cleaned rows: {len(df_clean)} (Removed {initial_rows - len(df_clean)} rows)")

# Step 6: Fill any remaining missing sensor data (NaN)
print("\nStep 6: Handling missing values (ffill/bfill)...")
# We fill forward first (last known value), then backward for any gaps at the start
df_clean = df_clean.ffill().bfill().fillna(0)
print("  ✅ Missing values resolved")

# Step 7: Data quality summary
print("\nStep 7: Data quality check...")
cols_to_check = ['power_consumption', 'temperature', 'humidity']
if has_occupancy:
    cols_to_check.append('workers')

for col in cols_to_check:
    if col in df_clean.columns:
        print(f"  {col.replace('_', ' ').title():20}: Min {df_clean[col].min():.2f} | Max {df_clean[col].max():.2f}")

# Step 8: Final Chronological Sorting
print("\nStep 8: Final sorting by Company and Time...")
df_clean = df_clean.sort_values(['company_name', 'timestamp']).reset_index(drop=True)
print("  ✅ Data sorted successfully")

print("\n" + "="*70)
print("✅ CELL 4 COMPLETE: DATA READY FOR FEATURE ENGINEERING")
print("="*70)

# CELL 5: Feature Engineering (PRODUCTION-READY)

import pandas as pd
import numpy as np

print("\n" + "="*70)
print("FEATURE ENGINEERING")
print("="*70)

# Create a fresh copy
df_features = df_clean.copy()

# Step 1: Extract temporal features from timestamp
print("\nStep 1: Extracting temporal features...")
df_features['hour'] = df_features['timestamp'].dt.hour
df_features['minute'] = df_features['timestamp'].dt.minute
df_features['day_of_week'] = df_features['timestamp'].dt.dayofweek
df_features['month'] = df_features['timestamp'].dt.month

# Step 2: Cyclical Encoding (Crucial for the API to understand time loops)
print("Step 2: Creating cyclical encoding...")
df_features['hour_sin'] = np.sin(2 * np.pi * df_features['hour'] / 24)
df_features['hour_cos'] = np.cos(2 * np.pi * df_features['hour'] / 24)
df_features['day_sin'] = np.sin(2 * np.pi * df_features['day_of_week'] / 7)
df_features['day_cos'] = np.cos(2 * np.pi * df_features['day_of_week'] / 7)

# Step 3: Time Category Features (Proxy for Human Behavior)
print("Step 3: Creating time category features...")
df_features['is_morning'] = ((df_features['hour'] >= 6) & (df_features['hour'] < 12)).astype(int)
df_features['is_evening'] = ((df_features['hour'] >= 18) & (df_features['hour'] < 24)).astype(int)
df_features['is_peak_hour'] = ((df_features['hour'] >= 17) & (df_features['hour'] <= 21)).astype(int)

# Step 4: Weather & Interaction Features (The "Occupancy Substitute")
print("Step 4: Creating weather & interactions...")
# Heat index helps predict AC load spikes
df_features['heat_index'] = df_features['temperature'] + (df_features['humidity'] / 100) * 5
# Interaction: High Temp during Peak Hours usually means Maximum Load
df_features['temp_x_is_peak'] = df_features['temperature'] * df_features['is_peak_hour']

# Step 5: Historical Lag Features (Fixed for sequence logic)
print("Step 5: Creating historical lags (1h, 6h, 24h)...")
# We use groupby to ensure lags don't spill over from one company to another
for lag in [1, 4, 24]:
    df_features[f'power_lag_{lag}'] = df_features.groupby('company_name')['power_consumption'].shift(lag)

# Step 6: Rolling Statistics (Moving Averages)
print("Step 6: Creating rolling statistics...")
for window in [4, 24]:
    df_features[f'power_rolling_mean_{window}'] = df_features.groupby('company_name')['power_consumption'].transform(
        lambda x: x.rolling(window=window, min_periods=1).mean()
    )

# Step 7: Final Cleaning of NaNs (Lags create empty rows at the start)
print("Step 7: Handling missing values from shifts...")
# Crucial: Fill NaNs so the LSTM doesn't receive "Null" inputs
df_features = df_features.ffill().bfill().fillna(0)

# Step 8: Final Summary
print("\n" + "="*70)
print("✅ FEATURE ENGINEERING COMPLETE!")
print("="*70)
print(f"Final Feature Set: {df_features.columns.tolist()}")
print(f"Total Columns: {len(df_features.columns)}")

# CELL 6: Prepare Data for LSTM (PRODUCTION-READY)

from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split
import numpy as np
import joblib # Added to save scalers for your TypeScript backend

print("\n" + "="*70)
print("PREPARING DATA FOR LSTM")
print("="*70)

# Step 1: Identify Features and Target
print("\nStep 1: Identifying features...")

# We exclude 'metadata' columns that the model can't "read"
metadata_cols = ['company_name', 'date', 'timestamp']
# We include power_consumption in the features because LSTM needs previous power to predict next power
model_features = [col for col in df_features.columns if col not in metadata_cols]

# Store the column names! Your TypeScript/Python API will need this exact list.
feature_list = model_features.copy()
print(f"  ✅ Using {len(feature_list)} features per timestep.")

# Step 2: Separate and Scale
print("\nStep 2: Normalizing data...")
# Extract values
data_values = df_features[feature_list].values
target_values = df_features[['power_consumption']].values

# Create Scalers
feature_scaler = MinMaxScaler()
target_scaler = MinMaxScaler()

# Fit and Transform
features_scaled = feature_scaler.fit_transform(data_values)
target_scaled = target_scaler.fit_transform(target_values)

# SAVE SCALERS IMMEDIATELY (You will need these files for your Python API!)
joblib.dump(feature_scaler, 'feature_scaler.pkl')
joblib.dump(target_scaler, 'target_scaler.pkl')
print("  ✅ Scalers saved as 'feature_scaler.pkl' and 'target_scaler.pkl'")

# Step 3: Create Sequences (Lookback)
print("\nStep 3: Creating sequences (Lookback = 24)...")
lookback = 24  # 6 hours of history (24 x 15-min)
X, y = [], []

# We iterate through the scaled data to create overlapping windows
for i in range(len(features_scaled) - lookback):
    X.append(features_scaled[i : i + lookback]) # The window of features
    y.append(target_scaled[i + lookback, 0])    # The NEXT hour's power (target)

X = np.array(X)
y = np.array(y)

print(f"  ✅ Total sequences created: {X.shape[0]}")
print(f"  ✅ Input Shape (Samples, Timesteps, Features): {X.shape}")

# Step 4: Time-Series Split (No Shuffling!)
print("\nStep 4: Splitting data (80/20)...")
# Important: We do NOT shuffle because time order matters!
split_idx = int(len(X) * 0.8)
X_train, X_test = X[:split_idx], X[split_idx:]
y_train, y_test = y[:split_idx], y[split_idx:]

print(f"  Train set: {X_train.shape}")
print(f"  Test set:  {X_test.shape}")

print("\n" + "="*70)
print("✅ DATA PREPARATION COMPLETE!")
print("="*70)

# CELL 7: Build LSTM Model (PRODUCTION-READY)

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dense, Dropout, BatchNormalization, Input
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.regularizers import l2

print("\n" + "="*70)
print("BUILDING LSTM MODEL ARCHITECTURE")
print("="*70)

# Define dimensions from our prepared data
n_timesteps = X_train.shape[1] # Should be 24
n_features = X_train.shape[2]  # Number of columns in our feature set

print(f"📊 Model Input Configuration:")
print(f"   Lookback Window: {n_timesteps} steps (6 hours)")
print(f"   Features/Step:   {n_features}")

# Build LSTM model
model = Sequential([
    # Use Input layer for clarity (Standard in newer Keras/TF versions)
    Input(shape=(n_timesteps, n_features)),

    # First LSTM layer - tanh is essential for GPU acceleration (cuDNN)
    LSTM(128, activation='tanh', return_sequences=True, kernel_regularizer=l2(0.001)),
    BatchNormalization(),
    Dropout(0.2),

    # Second LSTM layer
    LSTM(64, activation='tanh', return_sequences=True),
    BatchNormalization(),
    Dropout(0.2),

    # Third LSTM layer - return_sequences=False because we want a single output
    LSTM(32, activation='tanh', return_sequences=False),
    BatchNormalization(),
    Dropout(0.1),

    # Fully Connected (Dense) layers for the final "Peak" calculation
    Dense(32, activation='relu'),
    Dense(16, activation='relu'),
    Dense(1) # Final Output: The predicted Power Consumption (kW)
])

# Compile model
# Using Adam optimizer with a slightly lower learning rate for better convergence
print("\nCompiling model...")
model.compile(
    optimizer=Adam(learning_rate=0.0005),
    loss='mse', # Mean Squared Error is best for power prediction
    metrics=['mae', 'mape'] # Adding MAPE (Mean Absolute Percentage Error) to see % accuracy
)

print("\n✅ LSTM Architecture built successfully!")
print(f"   Ready to predict peak consumption for {n_features} variables.")
print("-" * 70)

# Display the summary to see the total "Trainable Parameters"
model.summary()

# CELL 8: Train LSTM Model (PRODUCTION-READY)

from tensorflow.keras.callbacks import EarlyStopping, ReduceLROnPlateau
import time

print("\n" + "="*70)
print("TRAINING LSTM MODEL")
print("="*70)

# Step 1: Verification & Pre-flight Checks
print("\nStep 1: Verifying model and data readiness...")
try:
    # Check if model and data exist in memory
    params = model.count_params()
    data_points = X_train.shape[0]
    print(f"   ✅ Model Verified ({params:,} parameters)")
    print(f"   ✅ Data Verified ({data_points} training sequences)")
except NameError:
    print("   ❌ ERROR: Model or Data not found! Please run Cells 6 & 7 first.")
    raise

# Step 2: Define Callbacks for Backend Stability
# These ensure the model doesn't "over-train" and stay lightweight
print("\nStep 2: Configuring Training Callbacks...")

early_stop = EarlyStopping(
    monitor='val_loss',
    patience=12,             # Stop if no improvement for 12 epochs
    restore_best_weights=True, # Critical: Keeps the most accurate version of the model
    verbose=1
)

reduce_lr = ReduceLROnPlateau(
    monitor='val_loss',
    factor=0.2,              # Aggressive reduction to find the "Peak" accuracy
    patience=5,
    min_lr=1e-6,
    verbose=1
)

# Step 3: Training Execution
# Note: Batch size 32 is ideal for the memory limits we set in Cell 0
EPOCHS = 100
BATCH_SIZE = 32

print(f"\nStep 3: Starting training (Max {EPOCHS} Epochs)...")
print("-" * 70)

start_time = time.time()

try:
    history = model.fit(
        X_train, y_train,
        validation_data=(X_test, y_test),
        epochs=EPOCHS,
        batch_size=BATCH_SIZE,
        callbacks=[early_stop, reduce_lr],
        shuffle=True,  # Shuffling sequences helps the model learn patterns, not just dates
        verbose=1
    )

    training_duration = (time.time() - start_time) / 60

    print("\n" + "="*70)
    print("✅ TRAINING COMPLETED SUCCESSFULLY!")
    print("="*70)
    print(f"⏱️ Training Time: {training_duration:.2f} minutes")
    print(f"📈 Total Epochs: {len(history.history['loss'])}")
    print(f"📉 Final Val Loss (MSE): {history.history['val_loss'][-1]:.6f}")
    print(f"🎯 Final Val MAE: {history.history['val_mae'][-1]:.6f}")

except Exception as e:
    print(f"\n❌ Error during training execution: {e}")
    raise

# CELL 9: Evaluate Model Performance (PRODUCTION-READY)

from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score, mean_absolute_percentage_error
from tensorflow.keras.models import load_model
import joblib
import numpy as np

print("\n" + "="*70)
print("MODEL EVALUATION & ACCURACY REPORT")
print("="*70)

# --- Step 0: Robust Model & Scaler Verification ---
print("\nStep 0: Checking for model and scalers...")

# Prioritize the model currently in memory from Cell 8
if 'model' in globals():
    print("   ✅ Active Model detected in memory.")
else:
    print("   🔍 Model not in memory. Attempting to load 'lstm_model.h5'...")
    try:
        model = load_model('lstm_model.h5')
        print("   ✅ Model loaded from disk.")
    except:
        print("   ❌ FATAL: No model found. Please run Cell 8 first!")
        raise NameError("Model undefined.")

# Ensure scalers are available for denormalization
try:
    if 'target_scaler' not in globals():
        target_scaler = joblib.load('target_scaler.pkl')
    print("   ✅ Target Scaler verified.")
except:
    print("   ❌ FATAL: target_scaler.pkl not found! Run Cell 6.")
    raise FileNotFoundError("Scaler missing.")

# --- Step 1: Generate Predictions ---
print("\nStep 1: Generating Predictions (Training & Test sets)...")
y_pred_train = model.predict(X_train, verbose=0)
y_pred_test = model.predict(X_test, verbose=0)

# --- Step 2: Denormalization (Converting 0-1 back to kW) ---
print("Step 2: Reversing normalization for real-world units (kW)...")

# Reshape y_train/y_test to match scaler expectations
y_train_raw = y_train.reshape(-1, 1)
y_test_raw = y_test.reshape(-1, 1)

# Inverse Transform
y_train_actual = target_scaler.inverse_transform(y_train_raw)
y_test_actual = target_scaler.inverse_transform(y_test_raw)
y_train_pred = target_scaler.inverse_transform(y_pred_train)
y_test_pred = target_scaler.inverse_transform(y_pred_test)

print("   ✅ Units converted back to Power (kW)")

# --- Step 3: Performance Metrics Calculation ---
def get_performance(actual, pred):
    mae = mean_absolute_error(actual, pred)
    rmse = np.sqrt(mean_squared_error(actual, pred))
    r2 = r2_score(actual, pred)
    mape = mean_absolute_percentage_error(actual, pred) * 100 # Convert to %
    return mae, rmse, r2, mape

tr_mae, tr_rmse, tr_r2, tr_mape = get_performance(y_train_actual, y_train_pred)
ts_mae, ts_rmse, ts_r2, ts_mape = get_performance(y_test_actual, y_test_pred)

# --- Step 4: Final Accuracy Report ---
print("\n" + "="*70)
print("             FINAL PERFORMANCE METRICS")
print("="*70)
print(f"{'Metric':<15} | {'Training Set':<15} | {'Test Set':<15}")
print("-" * 50)
print(f"{'R² Score':<15} | {tr_r2:<15.4f} | {ts_r2:<15.4f}")
print(f"{'MAE (kW)':<15} | {tr_mae:<15.2f} | {ts_mae:<15.2f}")
print(f"{'RMSE (kW)':<15} | {tr_rmse:<15.2f} | {ts_rmse:<15.2f}")
print(f"{'Accuracy (%)':<15} | {100-tr_mape:<15.2f}% | {100-ts_mape:<15.2f}%")
print("-" * 50)

# --- Step 5: Professional Assessment ---
print("\nGrade Assessment:")
if ts_r2 > 0.85:
    print("🏆 STATUS: EXCELLENT. Ready for production deployment.")
elif ts_r2 > 0.70:
    print("📈 STATUS: GOOD. Reliable for general trend forecasting.")
else:
    print("⚠️ STATUS: NEEDS TUNING. Check data quality or increase training epochs.")

print("\n" + "="*70)

# CELL 10: Visual Performance Analytics (PRODUCTION-READY)

import matplotlib.pyplot as plt
import numpy as np

print("\n" + "="*70)
print("GENERATING ANALYTIC VISUALIZATIONS")
print("="*70)

# Safety Check: Ensure history and variables exist
if 'history' not in globals():
    print("❌ ERROR: 'history' not found. Please run Training (Cell 8) first.")
    raise NameError("History undefined")

# Setup the Visualization Canvas
plt.style.use('seaborn-v0_8-muted') # Optional: cleaner styling
fig = plt.figure(figsize=(20, 14))

# --- Plot 1: Learning Curve (Loss) ---
print("Generating Plot 1: Learning Curve...")
ax1 = plt.subplot(2, 3, 1)
ax1.plot(history.history['loss'], label='Training Loss', linewidth=2.5, color='#2E86AB')
ax1.plot(history.history['val_loss'], label='Validation Loss', linewidth=2.5, color='#A23B72')
ax1.set_title('Learning Curve (MSE)', fontsize=14, fontweight='bold')
ax1.set_xlabel('Epochs')
ax1.set_ylabel('Loss')
ax1.legend()
ax1.grid(True, alpha=0.3)

# --- Plot 2: Error Trend (MAE) ---
print("Generating Plot 2: Error Trend...")
ax2 = plt.subplot(2, 3, 2)
ax2.plot(history.history['mae'], label='Train MAE', linewidth=2, color='#06A77D')
ax2.plot(history.history['val_mae'], label='Val MAE', linewidth=2, color='#D62828')
ax2.set_title('Mean Absolute Error (kW)', fontsize=14, fontweight='bold')
ax2.set_xlabel('Epochs')
ax2.legend()
ax2.grid(True, alpha=0.3)

# --- Plot 3: Time Series Forecast (The "Money" Plot) ---
print("Generating Plot 3: Time Series Forecast...")
ax3 = plt.subplot(2, 3, 3)
# Show the last 150 samples (roughly 37 hours) to see the daily peaks clearly
samples_to_show = min(150, len(y_test_actual))
x_axis = np.arange(samples_to_show)

ax3.plot(x_axis, y_test_actual[-samples_to_show:], label='Actual Grid Load',
         color='#06A77D', linewidth=2, marker='o', markersize=4)
ax3.plot(x_axis, y_test_pred[-samples_to_show:], label='LSTM Prediction',
         color='#D62828', linewidth=2, linestyle='--', marker='x', markersize=4)
ax3.set_title(f'Actual vs Forecast (Last {samples_to_show} intervals)', fontsize=14, fontweight='bold')
ax3.set_ylabel('Power (kW)')
ax3.legend()
ax3.grid(True, alpha=0.3)

# --- Plot 4: Prediction Error Distribution ---
print("Generating Plot 4: Error Distribution...")
ax4 = plt.subplot(2, 3, 4)
residuals = (y_test_actual - y_test_pred).flatten()
ax4.hist(residuals, bins=50, color='#2E86AB', edgecolor='white', alpha=0.8)
ax4.axvline(0, color='black', linestyle='-', linewidth=1)
ax4.set_title('Residuals (Errors) Distribution', fontsize=14, fontweight='bold')
ax4.set_xlabel('Error (kW)')

# --- Plot 5: Prediction Correlation (Scatter) ---
print("Generating Plot 5: Correlation Scatter...")
ax5 = plt.subplot(2, 3, 5)
ax5.scatter(y_test_actual, y_test_pred, alpha=0.3, s=20, color='#A23B72')
# Reference line for "Perfect Prediction"
lims = [np.min([ax5.get_xlim(), ax5.get_ylim()]), np.max([ax5.get_xlim(), ax5.get_ylim()])]
ax5.plot(lims, lims, 'k--', alpha=0.75, zorder=0, label='Perfect Fit')
ax5.set_title('Prediction Accuracy Correlation', fontsize=14, fontweight='bold')
ax5.set_xlabel('Actual (kW)')
ax5.set_ylabel('Predicted (kW)')
ax5.legend()

# --- Plot 6: Cumulative Accuracy ---
print("Generating Plot 6: Error Magnitude...")
ax6 = plt.subplot(2, 3, 6)
abs_errors = np.abs(residuals)
ax6.hist(abs_errors, bins=50, color='#F18F01', edgecolor='white')
ax6.set_title('Absolute Error Magnitude', fontsize=14, fontweight='bold')
ax6.set_xlabel('Error Size (kW)')

plt.tight_layout()
plt.savefig('smart_grid_analysis.png', dpi=300)
plt.show()

print("\n" + "="*70)
print("✅ VISUAL ANALYTICS COMPLETE!")
print(f"📁 Analysis saved as 'smart_grid_analysis.png'")
print("="*70)

# CELL 11: Save Model & Production Artifacts (FINAL)

import os
import json
import joblib
from datetime import datetime

print("\n" + "="*70)
print("📦 SAVING MODEL & DEPLOYMENT ARTIFACTS")
print("="*70)

# Step 1: Create a dedicated 'models' directory
print("\nStep 1: Preparing storage...")
os.makedirs('models', exist_ok=True)
print("   ✅ 'models/' directory ready.")

# Step 2: Save the Trained LSTM Model
print("\nStep 2: Saving Keras model...")
try:
    model_path = 'models/energy_lstm_model.h5'
    model.save(model_path)
    print(f"   ✅ Model saved to {model_path} ({os.path.getsize(model_path)/1024/1024:.2f} MB)")
except Exception as e:
    print(f"   ❌ Error saving model: {e}")

# Step 3: Save Scalers (Critical for Backend Normalization)
print("\nStep 3: Saving scalers...")
try:
    joblib.dump(feature_scaler, 'models/feature_scaler.pkl')
    joblib.dump(target_scaler, 'models/target_scaler.pkl')
    print("   ✅ Scalers saved. (Required for API Input/Output)")
except Exception as e:
    print(f"   ❌ Error saving scalers: {e}")

# Step 4: Save Feature List (Ensures API sends data in correct order)
print("\nStep 4: Exporting feature metadata...")
try:
    # We use the 'feature_list' we defined in Cell 6 to ensure 100% consistency
    if 'feature_list' not in globals():
        # Fallback if list isn't in memory
        cols_to_drop = ['company_name', 'date', 'timestamp']
        feature_list = [c for c in df_features.columns if c not in cols_to_drop]

    with open('models/feature_columns.json', 'w') as f:
        json.dump(feature_list, f, indent=4)
    print(f"   ✅ Saved {len(feature_list)} feature names to feature_columns.json")
except Exception as e:
    print(f"   ❌ Error saving feature list: {e}")

# Step 5: Save Production Metadata
print("\nStep 5: Generating metadata.json...")
try:
    metadata = {
        "project": "Smart Grid Energy Prediction",
        "version": "1.0.0",
        "timestamp": datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
        "model_architecture": "LSTM (3-Layer)",
        "input_shape": {
            "timesteps": int(X_train.shape[1]),
            "features": int(X_train.shape[2])
        },
        "performance_metrics": {
            "test_mae": float(ts_mae),
            "test_accuracy_pct": float(100 - ts_mape),
            "test_r2": float(ts_r2)
        },
        "feature_order": feature_list
    }

    with open('models/metadata.json', 'w') as f:
        json.dump(metadata, f, indent=4)
    print("   ✅ Metadata generated. (Useful for Backend version control)")
except Exception as e:
    print(f"   ❌ Error generating metadata: {e}")

print("\n" + "="*70)
print("🚀 ALL ARTIFACTS READY FOR DOWNLOAD")
print("="*70)
print("Files in 'models/' folder:")
print(os.listdir('models'))

# CELL 12: Real-Time Forecasting Simulation (PRODUCTION LOGIC)

import numpy as np
import pandas as pd

print("\n" + "="*70)
print("🔮 GENERATING SMART GRID FORECASTS")
print("="*70)

def predict_energy_step(input_sequence):
    """
    Takes a 24-step sequence and returns a single 1-step prediction.
    This mimics how your Python API will handle a request from TypeScript.
    """
    # Reshape for LSTM: (1 sample, 24 timesteps, N features)
    X_input = input_sequence.reshape(1, input_sequence.shape[0], input_sequence.shape[1])

    # Predict & Denormalize
    pred_scaled = model.predict(X_input, verbose=0)
    prediction_kw = target_scaler.inverse_transform(pred_scaled)[0][0]

    return prediction_kw

# --- 24-Hour Recursive Forecast Simulation ---
print("\nStep 1: Simulating a 24-hour 'look-ahead' forecast...")

# We'll take the very last sequence from our test set as the 'Current State'
current_sequence = X_test[-1].copy()
forecast_results = []

# For a true 24-hour forecast, we'd need future weather/time features.
# In this simulation, we'll keep features constant but update the 'Power' feedback loop.
for i in range(24):
    # 1. Get prediction for the next 15-minute interval
    next_val_kw = predict_energy_step(current_sequence)
    forecast_results.append(next_val_kw)

    # 2. Re-scale the prediction to put it back into the sequence
    next_val_scaled = target_scaler.transform([[next_val_kw]])[0][0]

    # 3. UPDATE THE SEQUENCE (The "Sliding Window")
    # We remove the oldest row and add the new prediction at the bottom
    new_row = current_sequence[-1].copy() # Copy the feature row

    # Update the 'power_consumption' column in this new row
    # (Assuming power_consumption is the last column based on Cell 6 logic)
    new_row[-1] = next_val_scaled

    # Slide the window
    current_sequence = np.vstack([current_sequence[1:], new_row])

# --- Display Results ---
forecast_results = np.array(forecast_results)

print("\n" + "="*70)
print("             24-HOUR FORECAST REPORT")
print("="*70)
print(f"✅ Current Grid Load:  {y_test_actual[-1][0]:.2f} kW")
print(f"🚀 Predicted Peak:      {forecast_results.max():.2f} kW")
print(f"📉 Predicted Minimum:   {forecast_results.min():.2f} kW")
print(f"📊 Average Load:        {forecast_results.mean():.2f} kW")

# Identify Peak Timing
peak_idx = np.argmax(forecast_results)
print(f"⏰ Peak expected in:    {peak_idx * 15} minutes from now")

print("\n" + "="*70)
print("✅ FORECASTING LOGIC VERIFIED")
print("="*70)